/* ============================================================================
   DCP New York — local visual editor
   ----------------------------------------------------------------------------
   Serves the real site from disk and injects an editing overlay into the
   response. The overlay is injected at SERVE TIME: no .html file on disk ever
   contains editor markup, and tools/ is excluded from the deploy allowlist, so
   none of this can reach the published site.

       node tools/editor/server.js          → http://127.0.0.1:8787

   Add ?preview=1 to any URL to see the page with no editor chrome at all.
   ========================================================================== */

'use strict';

const http = require('http');
const fs   = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const PORT = Number(process.env.EDITOR_PORT || 8787);
const CONFIG_FILE = path.join(ROOT, 'site.config.json');

/* Folders that are never pages. */
const NOT_PAGES = new Set(['assets', 'tools', 'node_modules', '.git', '.github', '.originals']);

/* Pages generated by tools/build.sh. Everything else the editor rewrites in
   place, so adding a page needs no change to the build script. */
const BUILT_BY_SCRIPT = new Set(['index.html', 'events/index.html', 'newyork/index.html']);

const LABELS = {
  'index.html': 'Portraits',
  'events/index.html': 'Event',
  'newyork/index.html': 'New York',
  'headshots/index.html': 'Headshots',
  'contact/index.html': 'Contact',
  'client/index.html': 'Client',
};

const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.json': 'application/json',
  '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png',
  '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.ico': 'image/x-icon',
};

/* ---------------------------------------------------------------- helpers */

const pad2 = n => String(n).padStart(2, '0');
const titleCase = s => s.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
const slugify = s => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

function send(res, code, body, type) {
  res.writeHead(code, { 'Content-Type': type || 'text/plain; charset=utf-8' });
  res.end(body);
}
const sendJson = (res, code, obj) =>
  send(res, code, JSON.stringify(obj, null, 2), 'application/json');

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = []; let size = 0;
    req.on('data', c => {
      size += c.length;
      if (size > 60 * 1024 * 1024) { reject(new Error('upload too large (60MB limit)')); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

function run(cmd, args) {
  return new Promise(resolve => {
    execFile(cmd, args, { cwd: ROOT, maxBuffer: 10 * 1024 * 1024 }, (err, stdout, stderr) =>
      resolve({ ok: !err, stdout: stdout || '', stderr: stderr || '' }));
  });
}
const git = args => run('git', args);

/* Width/height from the JPEG header, so no image library is needed. */
function jpegSize(buf) {
  if (buf.length < 4 || buf[0] !== 0xFF || buf[1] !== 0xD8) return null;
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xFF) { i++; continue; }
    const m = buf[i + 1];
    if (m >= 0xC0 && m <= 0xCF && m !== 0xC4 && m !== 0xC8 && m !== 0xCC) {
      return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
    }
    const len = buf.readUInt16BE(i + 2);
    if (len < 2) return null;
    i += 2 + len;
  }
  return null;
}

function readConfig() {
  try { return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8')); }
  catch (_) { return { galleries: {} }; }
}
const writeConfig = cfg => fs.writeFileSync(CONFIG_FILE, JSON.stringify(cfg, null, 2) + '\n', 'utf8');

/* ------------------------------------------------------- page discovery */

/* Every page is found on disk, so a page added through the editor shows up
   without anything being registered by hand. */
function discoverPages() {
  const found = [];

  if (fs.existsSync(path.join(ROOT, 'index.html'))) {
    found.push({ slug: '', path: 'index.html', url: '/' });
  }
  for (const d of fs.readdirSync(ROOT, { withFileTypes: true })) {
    if (!d.isDirectory() || d.name.startsWith('.') || NOT_PAGES.has(d.name)) continue;
    if (!fs.existsSync(path.join(ROOT, d.name, 'index.html'))) continue;
    found.push({ slug: d.name, path: `${d.name}/index.html`, url: `/${d.name}/` });
  }

  const cfg = readConfig();
  return found.map(p => {
    const html = fs.readFileSync(path.join(ROOT, p.path), 'utf8');
    const imgDir = p.slug ? `assets/img/${p.slug}` : 'assets/img/portraits';
    const hasImages = fs.existsSync(path.join(ROOT, imgDir));

    let type = null;
    if (html.includes('headshot-grid')) type = 'grid';
    else if (html.includes('carousel__track')) type = 'carousel';

    return Object.assign({}, p, {
      label: (cfg.pages && cfg.pages[p.path] && cfg.pages[p.path].label)
             || LABELS[p.path] || titleCase(p.slug),
      gallery: (type && hasImages) ? (p.slug || 'portraits') : null,
      dir: imgDir,
      type,
      builtByScript: BUILT_BY_SCRIPT.has(p.path),
    });
  });
}

const pageByGallery = name => discoverPages().find(p => p.gallery === name);
const pageByPath = rel => discoverPages().find(p => p.path === rel);

function listGallery(name) {
  const p = pageByGallery(name);
  if (!p) return [];
  try {
    return fs.readdirSync(path.join(ROOT, p.dir)).filter(f => /\.jpe?g$/i.test(f)).sort();
  } catch (_) { return []; }
}

function gallerySettings(name) {
  const p = pageByGallery(name);
  const defaults = p && p.type === 'grid' ? { columns: 3 } : { showControls: true };
  return Object.assign(defaults, (readConfig().galleries || {})[name] || {});
}

function publishedSet() {
  try {
    const wf = fs.readFileSync(path.join(ROOT, '.github/workflows/pages.yml'), 'utf8');
    const block = wf.match(/PUBLISH=\(([\s\S]*?)\)/);
    if (!block) return null;
    return new Set(block[1].split('\n').map(s => s.trim()).filter(Boolean));
  } catch (_) { return null; }
}

const NAV = require(path.join(ROOT, 'tools', 'nav.js'));

const navOrder = () => NAV.navItems().map(i => i.path);
const menuSet = () => new Set(navOrder());

/* Rewrites the four menus inside a hand-written page. The generated pages get
   theirs from tools/build.sh, which calls the same module. */
function applyNavToPage(rel) {
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) return;

  const slug = rel === 'index.html' ? '' : rel.split('/')[0];
  const prefix = slug ? '../' : '';
  const home = slug ? '../' : './';
  let html = fs.readFileSync(abs, 'utf8');

  html = html.replace(
    /(<div class="nav-side nav-side--left">[\s\S]*?<\/button>\n)[\s\S]*?(\n[ \t]*<\/div>)/,
    (_m, head, tail) => head + NAV.emit('header-left', prefix, home, rel) + tail);

  html = html.replace(
    /(<div class="nav-side nav-side--right">\n)[\s\S]*?(\n[ \t]*<\/div>)/,
    (_m, head, tail) => head + NAV.emit('header-right', prefix, home, rel) + tail);

  html = html.replace(
    /(<button class="overlay-close[^>]*><\/button>\n)[\s\S]*?(\n[ \t]*<\/div>)/,
    (_m, head, tail) => head + NAV.emit('overlay', prefix, home, rel) + tail);

  html = html.replace(
    /(<nav class="footer__menu"[^>]*>\n)[\s\S]*?(\n[ \t]*<\/nav>)/,
    (_m, head, tail) => head + NAV.emit('footer', prefix, home, rel) + tail);

  fs.writeFileSync(abs, html, 'utf8');
}

/* Push the current menu into every page: build.sh for the generated ones,
   a direct rewrite for the rest. */
async function applyNavEverywhere() {
  const built = await run('bash', ['tools/build.sh']);
  discoverPages()
    .filter(p => !p.builtByScript)
    .forEach(p => applyNavToPage(p.path));
  return built;
}

/* ---------------------------------------------------- markup regeneration */

function slidesMarkup(page, files) {
  const prefix = page.slug ? '../' : '';
  return files.map(f => {
    const d = jpegSize(fs.readFileSync(path.join(ROOT, page.dir, f))) || { width: 1200, height: 800 };
    const alt = f.replace(/^\d+-/, '').replace(/\.jpe?g$/i, '').replace(/[-_]+/g, ' ');
    return `          <div class="carousel__slide"><img src="${prefix}${page.dir}/${f}" alt="${alt}" width="${d.width}" height="${d.height}" loading="lazy" draggable="false"></div>`;
  }).join('\n');
}

function gridMarkup(page, files) {
  const cols = gallerySettings(page.gallery).columns;
  const prefix = page.slug ? '../' : '';
  const rows = files.map((f, i) => {
    const d = jpegSize(fs.readFileSync(path.join(ROOT, page.dir, f))) || { width: 1600, height: 1600 };
    return `      <button class="headshot-cell js-lb-open" type="button" aria-label="View photo ${i + 1} of ${files.length} full size">\n` +
           `        <img src="${prefix}${page.dir}/${f}" alt="Professional headshot by DCP New York" width="${d.width}" height="${d.height}" loading="lazy">\n` +
           `      </button>`;
  });
  return `    <section class="headshot-grid" data-cols="${cols}">\n${rows.join('\n')}\n    </section>`;
}

async function regenerate(galleryName) {
  const page = pageByGallery(galleryName);
  if (!page) throw new Error('unknown gallery');

  if (page.builtByScript) return run('bash', ['tools/build.sh']);

  const file = path.join(ROOT, page.path);
  let html = fs.readFileSync(file, 'utf8');
  const files = listGallery(galleryName);

  if (page.type === 'grid') {
    const re = /[ \t]*<section class="headshot-grid"[^>]*>[\s\S]*?<\/section>/;
    if (!re.test(html)) throw new Error('photo grid not found in ' + page.path);
    html = html.replace(re, gridMarkup(page, files));
  } else {
    const re = /(<div class="carousel__track">)([\s\S]*?)(\n[ \t]*<\/div>)/;
    if (!re.test(html)) throw new Error('carousel not found in ' + page.path);
    html = html.replace(re, (_m, open, _mid, close) =>
      open + (files.length ? '\n' + slidesMarkup(page, files) : '') + close);
  }

  fs.writeFileSync(file, html, 'utf8');
  return { ok: true, stdout: 'regenerated ' + page.path };
}

function applyOrder(galleryName, order) {
  const page = pageByGallery(galleryName);
  const dir = path.join(ROOT, page.dir);
  const existing = listGallery(galleryName);

  if (order.length !== existing.length || !order.every(f => existing.includes(f))) {
    throw new Error(
      'This page is out of step with the photo folder, so the order was not saved. ' +
      'Reload the page and try again.'
    );
  }

  const targets = order.map((file, i) => {
    const n = pad2(i + 1);
    const stem = page.type === 'grid' ? null : file.replace(/^\d+-/, '');
    return { from: file, to: stem ? `${n}-${stem}` : `headshot-${n}.jpg` };
  });

  const stamp = Date.now();
  targets.forEach((t, i) => fs.renameSync(path.join(dir, t.from), path.join(dir, `.tmp-${stamp}-${i}`)));
  targets.forEach((t, i) => fs.renameSync(path.join(dir, `.tmp-${stamp}-${i}`), path.join(dir, t.to)));
  return targets;
}

/* ------------------------------------------------------- new page template */

function newPageHtml(slug, label) {
  const title = `${label} | DCP New York`;
  const jsonld = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8')
    .match(/[ \t]*<script type="application\/ld\+json">[\s\S]*?<\/script>/)?.[0] || '';
  const src = fs.readFileSync(path.join(ROOT, 'contact/index.html'), 'utf8');
  const header = src.match(/[ \t]*<header class="site-header">[\s\S]*?<\/header>/)[0];
  const overlay = src.match(/[ \t]*<div class="overlay-menu[\s\S]*?<\/div>\n/)[0];
  const footer = src.match(/[ \t]*<footer class="site-footer">[\s\S]*?<\/footer>/)[0];
  const ver = (src.match(/style\.css\?v=(\d+)/) || [, '1'])[1];

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>${title}</title>
  <meta name="description" content="${label} photography by DCP New York.">
  <link rel="canonical" href="https://www.dcpnewyork.com/${slug}/">

  <meta property="og:site_name" content="DCP New York">
  <meta property="og:title" content="${title}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://www.dcpnewyork.com/${slug}/">
  <meta property="og:description" content="${label} photography by DCP New York.">
  <meta name="twitter:card" content="summary_large_image">

  <link rel="icon" href="../assets/img/logo.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../assets/css/style.css?v=${ver}">
${jsonld}
</head>
<body>
  <!--
    ============================================================
    NOT PUBLISHED YET.

    "${slug}" is absent from the PUBLISH list in
    .github/workflows/pages.yml, so this page stays in the repository and
    is never uploaded. It is also not linked from any navigation menu.

    To go live:
      1. add "${slug}" to PUBLISH in .github/workflows/pages.yml
      2. add nav links in tools/build.sh, contact/index.html and
         client/index.html, then rebuild
    ============================================================
  -->
${header}

${overlay}
  <main role="main">
    <section class="photo-slider">
      <div class="carousel js-carousel">
        <div class="carousel__track">
        </div>

        <button class="carousel__zone carousel__zone--prev js-prev" type="button" aria-label="Previous photo"></button>
        <button class="carousel__zone carousel__zone--next js-next" type="button" aria-label="Next photo"></button>

        <div class="carousel__nav">
          <button class="js-prev" type="button" aria-label="Previous photo">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 19l-7-7 7-7"/></svg>
          </button>
          <button class="js-next" type="button" aria-label="Next photo">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5l7 7-7 7"/></svg>
          </button>
        </div>
      </div>
    </section>
  </main>

${footer}

  <script src="../assets/js/site.js?v=${ver}"></script>
</body>
</html>
`;
}

/* ------------------------------------------------- editable text scanning */

function scanEditable(html) {
  const mainStart = html.indexOf('<main');
  const mainEnd = html.indexOf('</main>');
  if (mainStart === -1 || mainEnd === -1) return [];
  const slice = html.slice(mainStart, mainEnd);
  const re = /<(h1|h2|h3|h4|h5|h6|p)(\s[^>]*)?>([\s\S]*?)<\/\1>/g;
  const out = [];
  let m;
  while ((m = re.exec(slice))) {
    const innerStart = mainStart + m.index + m[0].indexOf('>', m[0].indexOf('<' + m[1])) + 1;
    out.push({ tag: m[1], start: innerStart, end: innerStart + m[3].length });
  }
  return out;
}

const hashOf = s => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h * 33) ^ s.charCodeAt(i)) >>> 0;
  return String(h);
};
const escapeHtml = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* ---------------------------------------------------------------- serving */

const editableMaps = new Map();

function injectEditor(html, pagePath) {
  const ranges = scanEditable(html);
  editableMaps.set(pagePath, { hash: hashOf(html), ranges });

  let out = '', cursor = 0;
  ranges.forEach((r, i) => {
    const openStart = html.lastIndexOf('<', r.start - 1);
    out += html.slice(cursor, openStart);
    out += html.slice(openStart, r.start).replace(/>$/, ` data-ed="${i}">`);
    cursor = r.start;
  });
  out += html.slice(cursor);

  const page = pageByPath(pagePath);
  const boot = `
<link rel="stylesheet" href="/__editor/editor.css">
<script>window.__EDITOR__=${JSON.stringify({ page: pagePath, gallery: page ? page.gallery : null })};</script>
<script src="/__editor/editor.js"></script>
`;
  return out.includes('</body>') ? out.replace('</body>', boot + '</body>') : out + boot;
}

/* -------------------------------------------------------------------- API */

async function handleApi(req, res, url, query) {
  const route = url.replace('/__editor/api/', '');

  if (route === 'status') {
    const [status, branch, ahead] = await Promise.all([
      git(['status', '--porcelain']),
      git(['rev-parse', '--abbrev-ref', 'HEAD']),
      git(['rev-list', '--count', '@{u}..HEAD']),
    ]);
    const changed = status.stdout.split('\n').map(s => s.trim()).filter(Boolean);
    return sendJson(res, 200, {
      branch: branch.stdout.trim(),
      changed, changedCount: changed.length,
      unpushed: Number((ahead.stdout || '0').trim()) || 0,
    });
  }

  if (route === 'pages') {
    const published = publishedSet();
    const order = navOrder();
    const inMenu = new Set(order);

    /* Menu pages come back in menu order, not alphabetically, so the list
       mirrors what a visitor sees. The rest follow, alphabetically. */
    const all = discoverPages().map(p => ({
      path: p.path, url: p.url, label: p.label, gallery: p.gallery, type: p.type,
      photos: p.gallery ? listGallery(p.gallery).length : 0,
      inMenu: inMenu.has(p.path),
      published: published ? published.has(p.slug || 'index.html') : true,
    }));

    const menu = order.map(pp => all.find(p => p.path === pp)).filter(Boolean);
    const rest = all.filter(p => !inMenu.has(p.path))
                    .sort((a, b) => a.label.localeCompare(b.label));

    return sendJson(res, 200, { pages: menu.concat(rest), nav: order });
  }

  if (route === 'settings' && req.method === 'GET') {
    const gallery = query.get('gallery');
    const page = pageByGallery(gallery);
    if (!page) return sendJson(res, 400, { error: 'unknown gallery' });
    return sendJson(res, 200, {
      gallery, type: page.type, settings: gallerySettings(gallery), photos: listGallery(gallery),
    });
  }

  if (req.method !== 'POST') return sendJson(res, 405, { error: 'POST required' });

  /* Upload writes the file and returns immediately. Resizing and rebuilding
     happen once in `finalize`, so dropping twelve photos spawns PowerShell
     once rather than twelve times. */
  if (route === 'gallery/upload') {
    const gallery = req.headers['x-gallery'];
    const rawName = String(req.headers['x-filename'] || 'photo.jpg');
    const page = pageByGallery(gallery);
    if (!page) return sendJson(res, 400, { error: 'unknown gallery' });

    const buf = await readBody(req);
    if (!jpegSize(buf)) return sendJson(res, 400, { error: `${rawName} is not a JPEG` });

    const next = listGallery(gallery).length + 1;
    const stem = rawName.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'photo';
    const name = page.type === 'grid' ? `headshot-${pad2(next)}.jpg` : `${pad2(next)}-${stem}.jpg`;

    fs.writeFileSync(path.join(ROOT, page.dir, name), buf);
    return sendJson(res, 200, { added: name });
  }

  if (route === 'gallery/finalize') {
    const { gallery } = JSON.parse((await readBody(req)).toString('utf8') || '{}');
    const page = pageByGallery(gallery);
    if (!page) return sendJson(res, 400, { error: 'unknown gallery' });

    const resize = await run('powershell', [
      '-NoProfile', '-ExecutionPolicy', 'Bypass',
      '-File', path.join('tools', 'resize-images.ps1'), '-Folder', page.dir,
    ]);
    const rebuild = await regenerate(gallery);
    return sendJson(res, 200, { ok: true, resize: resize.stdout.trim(), rebuild: rebuild.ok });
  }

  const body = JSON.parse((await readBody(req)).toString('utf8') || '{}');

  /* ---- reorder the site menu ---- */
  if (route === 'nav') {
    const order = Array.isArray(body.order) ? body.order : null;
    if (!order) return sendJson(res, 400, { error: 'an order is required' });

    const known = new Set(discoverPages().map(p => p.path));
    const bad = order.filter(p => !known.has(p));
    if (bad.length) return sendJson(res, 400, { error: 'unknown page: ' + bad[0] });

    /* A page that is not deployed must not be linked, or the live site gets a
       menu item that 404s for every visitor. */
    const published = publishedSet();
    if (published) {
      const draft = order.find(p => {
        const page = discoverPages().find(x => x.path === p);
        return page && !published.has(page.slug || 'index.html');
      });
      if (draft) {
        const label = discoverPages().find(x => x.path === draft).label;
        return sendJson(res, 400, {
          error: `"${label}" is a draft and is not on the live site, so it cannot go in the menu yet. ` +
                 `Add it to the PUBLISH list in .github/workflows/pages.yml first.`,
        });
      }
    }
    if (!order.includes('index.html')) {
      return sendJson(res, 400, { error: 'the home page has to stay in the menu' });
    }

    const cfg = readConfig();
    cfg.nav = order;
    writeConfig(cfg);

    const built = await applyNavEverywhere();
    return sendJson(res, 200, { ok: true, nav: order, rebuild: built.ok });
  }

  if (route === 'pages/create') {
    const label = String(body.label || '').trim();
    if (!label) return sendJson(res, 400, { error: 'a page name is required' });
    const slug = slugify(label);
    if (!slug) return sendJson(res, 400, { error: 'that name has no usable letters or numbers' });
    if (NOT_PAGES.has(slug)) return sendJson(res, 400, { error: `"${slug}" is a reserved folder name` });
    if (fs.existsSync(path.join(ROOT, slug))) return sendJson(res, 400, { error: `a page or folder called "${slug}" already exists` });

    fs.mkdirSync(path.join(ROOT, slug), { recursive: true });
    fs.mkdirSync(path.join(ROOT, 'assets/img', slug), { recursive: true });
    fs.writeFileSync(path.join(ROOT, slug, 'index.html'), newPageHtml(slug, label), 'utf8');
    fs.writeFileSync(path.join(ROOT, 'assets/img', slug, '.gitkeep'),
      `Photos for the "${label}" page. Named NN-name.jpg; the number sets the order.\n`);

    /* Hold the photos back. A draft page is not deployed, but everything
       under assets/ is published wholesale, so without this its photos would
       be reachable at their direct URLs the moment they were committed. The
       rule is removed when the page is launched. */
    const ignorePath = path.join(ROOT, '.gitignore');
    const rule = `/assets/img/${slug}/*.jpg`;
    let ignore = fs.existsSync(ignorePath) ? fs.readFileSync(ignorePath, 'utf8') : '';
    if (!ignore.includes(rule)) {
      ignore = ignore.replace(/\s*$/, '\n') +
        `\n# Photos for the draft "${label}" page. Delete this line when it launches.\n${rule}\n`;
      fs.writeFileSync(ignorePath, ignore, 'utf8');
    }

    const cfg = readConfig();
    cfg.pages = cfg.pages || {};
    cfg.pages[`${slug}/index.html`] = { label };
    writeConfig(cfg);

    return sendJson(res, 200, { ok: true, slug, url: `/${slug}/`, label, photosHeldBack: true });
  }

  if (route === 'gallery/reorder') {
    const { gallery, order } = body;
    if (!pageByGallery(gallery)) return sendJson(res, 400, { error: 'unknown gallery' });
    try {
      const moved = applyOrder(gallery, order);
      const rebuild = await regenerate(gallery);
      /* Hand back the new names. Reordering renames every file, so without
         this the page would keep sending the old ones and the next drag
         would be rejected. */
      return sendJson(res, 200, {
        ok: true, moved: moved.length, rebuild: rebuild.ok, files: listGallery(gallery),
      });
    } catch (e) { return sendJson(res, 400, { error: e.message }); }
  }

  if (route === 'gallery/delete') {
    const { gallery, file } = body;
    const page = pageByGallery(gallery);
    if (!page) return sendJson(res, 400, { error: 'unknown gallery' });
    const target = path.join(ROOT, page.dir, path.basename(file));
    if (!fs.existsSync(target)) return sendJson(res, 404, { error: 'file not found' });

    const bin = path.join(ROOT, '.originals', 'removed');
    fs.mkdirSync(bin, { recursive: true });
    fs.copyFileSync(target, path.join(bin, `${Date.now()}-${path.basename(file)}`));
    fs.unlinkSync(target);

    applyOrder(gallery, listGallery(gallery));
    const rebuild = await regenerate(gallery);
    return sendJson(res, 200, { ok: true, remaining: listGallery(gallery).length, rebuild: rebuild.ok });
  }

  if (route === 'settings') {
    const { gallery, settings } = body;
    if (!pageByGallery(gallery)) return sendJson(res, 400, { error: 'unknown gallery' });
    const cfg = readConfig();
    cfg.galleries = cfg.galleries || {};
    cfg.galleries[gallery] = Object.assign(gallerySettings(gallery), settings || {});
    writeConfig(cfg);
    const rebuild = await regenerate(gallery);
    return sendJson(res, 200, { ok: true, settings: cfg.galleries[gallery], rebuild: rebuild.ok });
  }

  if (route === 'text') {
    const { page, index, text } = body;
    const abs = path.join(ROOT, page);
    if (!abs.startsWith(ROOT) || !fs.existsSync(abs)) return sendJson(res, 400, { error: 'unknown page' });
    const html = fs.readFileSync(abs, 'utf8');
    const map = editableMaps.get(page);
    if (!map || map.hash !== hashOf(html)) {
      return sendJson(res, 409, { error: 'the page changed on disk since it was loaded — reload and try again' });
    }
    const r = map.ranges[index];
    if (!r) return sendJson(res, 400, { error: 'unknown text block' });
    fs.writeFileSync(abs, html.slice(0, r.start) + escapeHtml(text) + html.slice(r.end), 'utf8');
    editableMaps.delete(page);
    return sendJson(res, 200, { ok: true });
  }

  if (route === 'publish') {
    const message = (body.message || '').trim() || 'Update site content';
    const log = [];
    const add = await git(['add', '-A']);
    log.push('$ git add -A', add.stdout + add.stderr);

    const staged = await git(['diff', '--cached', '--name-only']);
    if (!staged.stdout.trim()) {
      const push = await git(['push']);
      log.push('$ git push', push.stdout + push.stderr);
      return sendJson(res, 200, { ok: push.ok, nothingToCommit: true, log: log.join('\n') });
    }
    const commit = await git(['commit', '-m', message]);
    log.push('$ git commit', commit.stdout + commit.stderr);
    if (!commit.ok) return sendJson(res, 500, { ok: false, log: log.join('\n') });
    const push = await git(['push']);
    log.push('$ git push', push.stdout + push.stderr);
    return sendJson(res, push.ok ? 200 : 500, { ok: push.ok, log: log.join('\n') });
  }

  return sendJson(res, 404, { error: 'unknown endpoint' });
}

/* ------------------------------------------------------------------ server */

http.createServer(async (req, res) => {
  try {
    const [rawPath, rawQuery] = req.url.split('?');
    const query = new URLSearchParams(rawQuery || '');

    if (rawPath.startsWith('/__editor/api/')) return await handleApi(req, res, rawPath, query);

    if (rawPath === '/__editor/editor.css' || rawPath === '/__editor/editor.js') {
      const file = path.join(__dirname, path.basename(rawPath));
      return send(res, 200, fs.readFileSync(file), TYPES[path.extname(file)]);
    }

    let rel = decodeURIComponent(rawPath).replace(/^\/+/, '');
    if (rel === '' || rel.endsWith('/')) rel += 'index.html';
    let abs = path.join(ROOT, rel);
    if (!abs.startsWith(ROOT)) return send(res, 403, 'forbidden');
    if (fs.existsSync(abs) && fs.statSync(abs).isDirectory()) abs = path.join(abs, 'index.html');
    if (!fs.existsSync(abs)) return send(res, 404, 'Not found: ' + rel);

    if (path.extname(abs) === '.html') {
      const pageRel = path.relative(ROOT, abs).replace(/\\/g, '/');
      const html = fs.readFileSync(abs, 'utf8');
      /* ?preview=1 serves the page exactly as it will be published. */
      const out = query.get('preview') ? html : injectEditor(html, pageRel);
      return send(res, 200, out, TYPES['.html']);
    }

    res.writeHead(200, {
      'Content-Type': TYPES[path.extname(abs)] || 'application/octet-stream',
      'Cache-Control': 'no-store',
    });
    fs.createReadStream(abs).pipe(res);
  } catch (e) {
    send(res, 500, 'Editor error: ' + e.message);
  }
}).listen(PORT, '127.0.0.1', () => {
  console.log('\n  DCP New York — visual editor');
  console.log('  ---------------------------------------------');
  console.log('  http://127.0.0.1:' + PORT);
  console.log('\n  Editing writes to the real files in this repo.');
  console.log('  Publish runs git add / commit / push.');
  console.log('  Stop with Ctrl+C.\n');
});
