/* ============================================================================
   DCP New York — local visual editor
   ----------------------------------------------------------------------------
   A small zero-dependency server that serves the real site from disk and
   injects an editing overlay into the response.

   The overlay is injected at SERVE TIME. The .html files on disk never contain
   a single line of editor markup, so there is no way for the editor to reach
   the published site. tools/ is also excluded from the deploy allowlist.

       node tools/editor/server.js          → http://127.0.0.1:8787

   Edits are written straight to the real files in the repository. "Publish"
   runs git add / commit / push, which is what puts them on the live site.
   ========================================================================== */

'use strict';

const http = require('http');
const fs   = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const PORT = Number(process.env.EDITOR_PORT || 8787);

/* Galleries the editor knows how to manage.
   carousel pages are regenerated by tools/build.sh from the folder contents;
   the headshots grid is regenerated in place by this server. */
const GALLERIES = {
  portraits: { dir: 'assets/img/portraits', page: 'index.html',           type: 'carousel' },
  events:    { dir: 'assets/img/events',    page: 'events/index.html',    type: 'carousel' },
  newyork:   { dir: 'assets/img/newyork',   page: 'newyork/index.html',   type: 'carousel' },
  headshots: { dir: 'assets/img/headshots', page: 'headshots/index.html', type: 'grid' },
};

const PAGE_TO_GALLERY = {};
for (const [name, g] of Object.entries(GALLERIES)) PAGE_TO_GALLERY[g.page] = name;

const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.json': 'application/json',
  '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png',
  '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.ico': 'image/x-icon',
};

/* ---------------------------------------------------------------- helpers */

const pad2 = n => String(n).padStart(2, '0');

function send(res, code, body, type) {
  res.writeHead(code, { 'Content-Type': type || 'text/plain; charset=utf-8' });
  res.end(body);
}
const sendJson = (res, code, obj) =>
  send(res, code, JSON.stringify(obj, null, 2), 'application/json');

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on('data', c => {
      size += c.length;
      if (size > 60 * 1024 * 1024) { reject(new Error('upload too large (60MB limit)')); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

function git(args) {
  return new Promise(resolve => {
    execFile('git', args, { cwd: ROOT, maxBuffer: 10 * 1024 * 1024 }, (err, stdout, stderr) => {
      resolve({ ok: !err, code: err ? (err.code ?? 1) : 0, stdout: stdout || '', stderr: stderr || '' });
    });
  });
}

function run(cmd, args, opts) {
  return new Promise(resolve => {
    execFile(cmd, args, Object.assign({ cwd: ROOT, maxBuffer: 10 * 1024 * 1024 }, opts || {}),
      (err, stdout, stderr) => resolve({ ok: !err, stdout: stdout || '', stderr: stderr || '' }));
  });
}

/* Width/height straight out of the JPEG header, so no image library needed. */
function jpegSize(buf) {
  if (buf.length < 4 || buf[0] !== 0xFF || buf[1] !== 0xD8) return null;
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xFF) { i++; continue; }
    const marker = buf[i + 1];
    if (marker >= 0xC0 && marker <= 0xCF && marker !== 0xC4 && marker !== 0xC8 && marker !== 0xCC) {
      return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
    }
    const len = buf.readUInt16BE(i + 2);
    if (len < 2) return null;
    i += 2 + len;
  }
  return null;
}

const listGallery = name =>
  fs.readdirSync(path.join(ROOT, GALLERIES[name].dir))
    .filter(f => /\.jpe?g$/i.test(f))
    .sort();

/* ------------------------------------------------- editable text scanning */

/* Finds the inner ranges of headings and paragraphs inside <main>. The same
   scan runs when serving (to number them) and when saving (to locate them),
   and the file hash is checked in between, so an index always refers to the
   same piece of text. */
function scanEditable(html) {
  const mainStart = html.indexOf('<main');
  const mainEnd = html.indexOf('</main>');
  if (mainStart === -1 || mainEnd === -1) return [];

  const slice = html.slice(mainStart, mainEnd);
  const re = /<(h1|h2|h3|h4|h5|h6|p)(\s[^>]*)?>([\s\S]*?)<\/\1>/g;
  const out = [];
  let m;
  while ((m = re.exec(slice))) {
    const innerStart = mainStart + m.index + m[0].indexOf('>', m[0].indexOf('<' + m[1])) + 1;
    out.push({ tag: m[1], start: innerStart, end: innerStart + m[3].length, text: m[3] });
  }
  return out;
}

const hashOf = s => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h * 33) ^ s.charCodeAt(i)) >>> 0;
  return String(h);
};

const escapeHtml = s =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* ----------------------------------------------------- markup regeneration */

function gridMarkup(files) {
  const total = files.length;
  const rows = files.map((f, i) => {
    const buf = fs.readFileSync(path.join(ROOT, GALLERIES.headshots.dir, f));
    const d = jpegSize(buf) || { width: 1600, height: 1600 };
    return [
      `      <button class="headshot-cell js-lb-open" type="button" aria-label="View photo ${i + 1} of ${total} full size">`,
      `        <img src="../assets/img/headshots/${f}" alt="Professional headshot by DCP New York" width="${d.width}" height="${d.height}" loading="lazy">`,
      `      </button>`,
    ].join('\n');
  });
  return '    <section class="headshot-grid">\n' + rows.join('\n') + '\n    </section>';
}

function regenerateGrid() {
  const file = path.join(ROOT, GALLERIES.headshots.page);
  const html = fs.readFileSync(file, 'utf8');
  const re = /[ \t]*<section class="headshot-grid">[\s\S]*?<\/section>/;
  if (!re.test(html)) throw new Error('headshot-grid section not found in headshots/index.html');
  fs.writeFileSync(file, html.replace(re, gridMarkup(listGallery('headshots'))), 'utf8');
}

async function regenerate(galleryName) {
  if (GALLERIES[galleryName].type === 'grid') { regenerateGrid(); return { ok: true, stdout: 'grid regenerated' }; }
  return run('bash', ['tools/build.sh']);
}

/* Renames every file so the numeric prefix matches the requested order. Goes
   via temporary names first so a swap cannot collide. */
function applyOrder(galleryName, order) {
  const g = GALLERIES[galleryName];
  const dir = path.join(ROOT, g.dir);
  const existing = listGallery(galleryName);

  if (order.length !== existing.length || !order.every(f => existing.includes(f))) {
    throw new Error('the requested order does not match the files on disk');
  }

  const targets = order.map((file, i) => {
    const n = pad2(i + 1);
    let next;
    if (g.type === 'grid') {
      next = `headshot-${n}.jpg`;
    } else {
      const stem = file.replace(/^\d+-/, '');
      next = `${n}-${stem}`;
    }
    return { from: file, to: next };
  });

  const stamp = Date.now();
  targets.forEach((t, i) => fs.renameSync(path.join(dir, t.from), path.join(dir, `.tmp-${stamp}-${i}`)));
  targets.forEach((t, i) => fs.renameSync(path.join(dir, `.tmp-${stamp}-${i}`), path.join(dir, t.to)));
  return targets;
}

/* ---------------------------------------------------------------- serving */

const editableMaps = new Map();   // page → { hash, ranges }

function injectEditor(html, pagePath) {
  const ranges = scanEditable(html);
  editableMaps.set(pagePath, { hash: hashOf(html), ranges });

  /* Number the editable elements in the SERVED copy only. */
  let out = '';
  let cursor = 0;
  ranges.forEach((r, i) => {
    const openStart = html.lastIndexOf('<', r.start - 1);
    out += html.slice(cursor, openStart);
    const openTag = html.slice(openStart, r.start);
    out += openTag.replace(/>$/, ` data-ed="${i}">`);
    cursor = r.start;
  });
  out += html.slice(cursor);

  const gallery = PAGE_TO_GALLERY[pagePath] || '';
  const boot = `
<link rel="stylesheet" href="/__editor/editor.css">
<script>window.__EDITOR__=${JSON.stringify({ page: pagePath, gallery })};</script>
<script src="/__editor/editor.js"></script>
`;
  return out.includes('</body>') ? out.replace('</body>', boot + '</body>') : out + boot;
}

function resolveRequest(urlPath) {
  let rel = decodeURIComponent(urlPath.split('?')[0]).replace(/^\/+/, '');
  if (rel === '' || rel.endsWith('/')) rel += 'index.html';
  const abs = path.join(ROOT, rel);
  if (!abs.startsWith(ROOT)) return null;            // no climbing out of the repo
  return { rel: rel.replace(/\\/g, '/'), abs };
}

/* -------------------------------------------------------------------- API */

async function handleApi(req, res, url) {
  const route = url.replace('/__editor/api/', '');

  if (route === 'status') {
    const [status, branch, ahead] = await Promise.all([
      git(['status', '--porcelain']),
      git(['rev-parse', '--abbrev-ref', 'HEAD']),
      git(['rev-list', '--count', '@{u}..HEAD']),
    ]);
    const changed = status.stdout.split('\n').map(s => s.trim()).filter(Boolean);
    return sendJson(res, 200, {
      branch: branch.stdout.trim(),
      changed,
      changedCount: changed.length,
      unpushed: Number((ahead.stdout || '0').trim()) || 0,
      galleries: Object.fromEntries(Object.keys(GALLERIES).map(k => [k, listGallery(k)])),
    });
  }

  if (req.method !== 'POST') return sendJson(res, 405, { error: 'POST required' });

  /* ---- image upload: raw bytes, filename in a header ---- */
  if (route === 'gallery/upload') {
    const gallery = req.headers['x-gallery'];
    const rawName = String(req.headers['x-filename'] || 'photo.jpg');
    if (!GALLERIES[gallery]) return sendJson(res, 400, { error: 'unknown gallery' });

    const buf = await readBody(req);
    const size = jpegSize(buf);
    if (!size) return sendJson(res, 400, { error: `${rawName} is not a JPEG. Save it as .jpg and try again.` });

    const g = GALLERIES[gallery];
    const next = listGallery(gallery).length + 1;
    const stem = rawName.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'photo';
    const name = g.type === 'grid' ? `headshot-${pad2(next)}.jpg` : `${pad2(next)}-${stem}.jpg`;

    fs.writeFileSync(path.join(ROOT, g.dir, name), buf);

    /* Shrink it the same way the rest of the site's photos were shrunk. */
    const resize = await run('powershell', [
      '-NoProfile', '-ExecutionPolicy', 'Bypass',
      '-File', path.join('tools', 'resize-images.ps1'),
      '-Folder', g.dir, '-Filter', name,
    ]);

    const result = await regenerate(gallery);
    return sendJson(res, 200, { added: name, resize: resize.stdout.trim(), rebuild: result.ok });
  }

  const body = JSON.parse((await readBody(req)).toString('utf8') || '{}');

  /* ---- reorder ---- */
  if (route === 'gallery/reorder') {
    const { gallery, order } = body;
    if (!GALLERIES[gallery]) return sendJson(res, 400, { error: 'unknown gallery' });
    try {
      const moved = applyOrder(gallery, order);
      const result = await regenerate(gallery);
      return sendJson(res, 200, { ok: true, moved: moved.length, rebuild: result.ok });
    } catch (e) { return sendJson(res, 400, { error: e.message }); }
  }

  /* ---- delete ---- */
  if (route === 'gallery/delete') {
    const { gallery, file } = body;
    if (!GALLERIES[gallery]) return sendJson(res, 400, { error: 'unknown gallery' });
    const target = path.join(ROOT, GALLERIES[gallery].dir, path.basename(file));
    if (!fs.existsSync(target)) return sendJson(res, 404, { error: 'file not found' });

    /* Keep a copy outside the repo rather than destroying the only one. */
    const bin = path.join(ROOT, '.originals', 'removed');
    fs.mkdirSync(bin, { recursive: true });
    fs.copyFileSync(target, path.join(bin, `${Date.now()}-${path.basename(file)}`));
    fs.unlinkSync(target);

    const remaining = listGallery(gallery);
    applyOrder(gallery, remaining);               // close the numbering gap
    const result = await regenerate(gallery);
    return sendJson(res, 200, { ok: true, remaining: remaining.length, rebuild: result.ok });
  }

  /* ---- text ---- */
  if (route === 'text') {
    const { page, index, text } = body;
    const abs = path.join(ROOT, page);
    if (!abs.startsWith(ROOT) || !fs.existsSync(abs)) return sendJson(res, 400, { error: 'unknown page' });

    const html = fs.readFileSync(abs, 'utf8');
    const map = editableMaps.get(page);
    if (!map || map.hash !== hashOf(html)) {
      return sendJson(res, 409, { error: 'the page changed on disk since it was loaded — reload and try again' });
    }
    const r = map.ranges[index];
    if (!r) return sendJson(res, 400, { error: 'unknown text block' });

    const next = html.slice(0, r.start) + escapeHtml(text) + html.slice(r.end);
    fs.writeFileSync(abs, next, 'utf8');
    editableMaps.delete(page);
    return sendJson(res, 200, { ok: true });
  }

  /* ---- publish ---- */
  if (route === 'publish') {
    const message = (body.message || '').trim() || 'Update site content';
    const log = [];

    const add = await git(['add', '-A']);
    log.push('$ git add -A', add.stdout + add.stderr);

    const staged = await git(['diff', '--cached', '--name-only']);
    if (!staged.stdout.trim()) {
      const push = await git(['push']);
      log.push('$ git push', push.stdout + push.stderr);
      return sendJson(res, 200, { ok: push.ok, nothingToCommit: true, log: log.join('\n') });
    }

    const commit = await git(['commit', '-m', message]);
    log.push('$ git commit', commit.stdout + commit.stderr);
    if (!commit.ok) return sendJson(res, 500, { ok: false, log: log.join('\n') });

    const push = await git(['push']);
    log.push('$ git push', push.stdout + push.stderr);
    return sendJson(res, push.ok ? 200 : 500, { ok: push.ok, log: log.join('\n') });
  }

  return sendJson(res, 404, { error: 'unknown endpoint' });
}

/* ------------------------------------------------------------------ server */

http.createServer(async (req, res) => {
  try {
    const url = req.url.split('?')[0];

    if (url.startsWith('/__editor/api/')) return await handleApi(req, res, url);

    if (url === '/__editor/editor.css' || url === '/__editor/editor.js') {
      const file = path.join(__dirname, path.basename(url));
      return send(res, 200, fs.readFileSync(file), TYPES[path.extname(file)]);
    }

    const target = resolveRequest(url);
    if (!target) return send(res, 403, 'forbidden');

    let abs = target.abs;
    if (fs.existsSync(abs) && fs.statSync(abs).isDirectory()) abs = path.join(abs, 'index.html');
    if (!fs.existsSync(abs)) return send(res, 404, 'Not found: ' + target.rel);

    if (path.extname(abs) === '.html') {
      const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
      const html = injectEditor(fs.readFileSync(abs, 'utf8'), rel);
      return send(res, 200, html, TYPES['.html']);
    }

    res.writeHead(200, {
      'Content-Type': TYPES[path.extname(abs)] || 'application/octet-stream',
      'Cache-Control': 'no-store',          // always show the file as it is now
    });
    fs.createReadStream(abs).pipe(res);
  } catch (e) {
    send(res, 500, 'Editor error: ' + e.message);
  }
}).listen(PORT, '127.0.0.1', () => {
  console.log('');
  console.log('  DCP New York — visual editor');
  console.log('  ---------------------------------------------');
  console.log('  http://127.0.0.1:' + PORT);
  console.log('');
  console.log('  Editing writes to the real files in this repo.');
  console.log('  Publish runs git add / commit / push.');
  console.log('  Stop with Ctrl+C.');
  console.log('');
});
